### ISSUE TITLE
Allow setting multiple jetty handlers

### ISSUE THREAD

**Issue by johanhaleby** [weavejester/ring-jetty-component#3]
In my experience it's very common to expose two different ports in your application. One is for the external API and another is for an admin/management API (see for example Dropwizard and Spring Boot). This way you can restrict access to the admin API by locking down the port to only be accessible from specific IP addresses or subnets. 

Today I've tried to implement this using ring-jetty-component but I fail to do so and looking at the source it seems to be more or less impossible. What I want to do is to create a two virtual hosts in Jetty where the external http interface consists of one set of compojure routes and the admin http interface contains another set of compojure routes _sharing the same_ Jetty instance.

**Comment by weavejester** [comment]
Why not use two Jetty components, each running on a separate port?

**Comment by johanhaleby** [comment]
This is what I've done as a workaround but it could potentially be a waste of resources (more threads are created, more memory is consumed etc). For example Dropwizard uses multiple handlers and I suspect that Spring Boot does the same.

**Comment by weavejester** [comment]
The thread count would be the only thing I'd be potentially worried about, but it's rare that the bottleneck in a web application is related to the HTTP server itself. Creating two server components if you want to bind to two different ports is the solution I'd reach for first, and only if I had a problem would I try optimising that part.

Because Ring-Jetty-Component just wraps Ring's Jetty adapter, and passes any options across verbatim, I'd suggest opening this issue on the Ring repository instead. The change you want would need to be implemented on the Ring Jetty adapter, rather than this wrapper library.

**Comment by johanhaleby** [comment]
Thanks for your feedback
